# Generated by Django 4.2.7 on 2023-11-13 14:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(default=api.models.generate_ids, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(default=api.models.generate_ids, max_length=128, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=68)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
