# Generated by Django 4.2.7 on 2023-12-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('statuses_count', models.IntegerField(default=0)),
                ('favourites_count', models.IntegerField(default=0)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('last_tweet_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('contributors_enabled', models.BooleanField(default=False)),
                ('is_premium_user', models.BooleanField(default=False)),
                ('preferred_theme', models.CharField(blank=True, max_length=20, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('has_geo_enabled', models.BooleanField(default=False)),
                ('is_translator', models.BooleanField(default=False)),
                ('default_profile', models.BooleanField(default=False)),
                ('default_profile_image', models.BooleanField(default=False)),
                ('listed_count', models.IntegerField(default=0)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('external_blog', models.URLField(blank=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='api.twitteruser')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_quote_tweet', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('in_reply_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to='api.twitteruser')),
                ('original_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='api.tweet')),
                ('quoted_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_tweets', to='api.tweet')),
                ('reply_to_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.twitteruser')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweets', models.ManyToManyField(to='api.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='feed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_feed', to='api.feed'),
        ),
    ]
